// <auto-generated />
using System;
using ClassLibrary2021;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary2021.Migrations
{
    [DbContext(typeof(HireContext))]
    [Migration("20260106132806_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary2021.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarID"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            Class = "Economy",
                            CostPerDay = 51.83m,
                            Make = "VW",
                            Model = "Polo"
                        },
                        new
                        {
                            CarID = 2,
                            Class = "Compact",
                            CostPerDay = 59.93m,
                            Make = "Ford",
                            Model = "Focus"
                        },
                        new
                        {
                            CarID = 3,
                            Class = "Compact",
                            CostPerDay = 56.87m,
                            Make = "Ford",
                            Model = "Puma"
                        },
                        new
                        {
                            CarID = 4,
                            Class = "Mini",
                            CostPerDay = 50.92m,
                            Make = "VW",
                            Model = "UP"
                        },
                        new
                        {
                            CarID = 5,
                            Class = "Standard",
                            CostPerDay = 66.22m,
                            Make = "Ford",
                            Model = "Kuga"
                        });
                });

            modelBuilder.Entity("ClassLibrary2021.Hire", b =>
                {
                    b.Property<int>("HireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HireID"));

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("DropOffLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExtraCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HireEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HireStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickUpLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HireID");

                    b.HasIndex("CarID");

                    b.ToTable("Hires");

                    b.HasData(
                        new
                        {
                            HireID = 1,
                            CarID = 1,
                            DropOffLocation = "Sligo",
                            ExtraCharge = 30m,
                            HireEndDate = new DateTime(2021, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireStartDate = new DateTime(2021, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocation = "Sligo"
                        },
                        new
                        {
                            HireID = 2,
                            CarID = 1,
                            DropOffLocation = "Dublin Airport",
                            ExtraCharge = 127.56m,
                            HireEndDate = new DateTime(2021, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireStartDate = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocation = "Sligo"
                        },
                        new
                        {
                            HireID = 3,
                            CarID = 5,
                            DropOffLocation = "Sligo",
                            ExtraCharge = 30m,
                            HireEndDate = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireStartDate = new DateTime(2022, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocation = "Sligo"
                        },
                        new
                        {
                            HireID = 4,
                            CarID = 5,
                            DropOffLocation = "Sligo",
                            ExtraCharge = 30m,
                            HireEndDate = new DateTime(2022, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HireStartDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocation = "Sligo"
                        });
                });

            modelBuilder.Entity("ClassLibrary2021.Hire", b =>
                {
                    b.HasOne("ClassLibrary2021.Car", "Car")
                        .WithMany("Hires")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("ClassLibrary2021.Car", b =>
                {
                    b.Navigation("Hires");
                });
#pragma warning restore 612, 618
        }
    }
}
